import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Bell, Building2, CheckCheck, ClipboardList, Download, FileText, FolderKanban, Gauge, Image, LayoutDashboard, LogOut, Menu, MessageSquare, Plus, RefreshCw, Search, Settings, Shield, Users, Wrench, X } from 'lucide-react'
import { api } from '../../01-FRONTEND/services/api'
import AdminInquiries from './AdminInquiries'

const nav = ['Dashboard','Users','Inquiries','Contact Messages','Projects','Services','Company Information','Website Content','Media Library','Documents','Admin Users','Notifications','Reports','Settings']
const navGroups = [{label:'Overview',items:['Dashboard']},{label:'Main',items:['Users','Inquiries','Contact Messages']},{label:'Content',items:['Projects','Services','Company Information','Website Content','Media Library','Documents']},{label:'Management',items:['Admin Users','Notifications','Reports']},{label:'System',items:['Settings']}]
const navIcons = {Dashboard:LayoutDashboard,Users,Inquiries:ClipboardList,'Contact Messages':MessageSquare,Projects:FolderKanban,Services:Wrench,'Company Information':Building2,'Website Content':FileText,'Media Library':Image,Documents:FileText,'Admin Users':Shield,Notifications:Bell,Reports:Activity,Settings}
const rolePermissions={super_admin:['*'],admin:['*'],manager:['Inquiries','Projects'],editor:['Services','Website Content','Media Library'],support_staff:['Inquiries','Contact Messages']}
const blankProject = {title:'',location:'',category:'Commercial',description:'',clientName:'',projectValue:'',startDate:'',completionDate:'',status:'Upcoming',image:'',brochure:'',displayOrder:0}
const blankService = {title:'',slug:'',description:'',image:'',icon:'',displayOrder:0,status:'active'}
const statusOptions = ['New','Contacted','In Discussion','Quoted','Follow-up','Converted','Rejected','Closed','Pending','In Progress','Responded','Resolved','Cancelled']
const niceDate = (value) => value ? new Date(value).toLocaleDateString() : '—'
const downloadCsv = (filename, rows) => {
  if (!rows.length) return
  const headers = Object.keys(rows[0]); const quote = (v) => `"${String(v ?? '').replaceAll('"','""')}"`
  const blob = new Blob([[headers.map(quote).join(','),...rows.map(row=>headers.map(key=>quote(row[key])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'})
  const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;link.click();URL.revokeObjectURL(link.href)
}

export default function AdminWorkspace({token,admin,onLogout}) {
  const allowed=rolePermissions[admin?.role]||[]
  const visible=(item)=>allowed.includes('*')||allowed.includes(item)
  const firstPage=visible('Dashboard')?'Dashboard':nav.find(visible)||'Dashboard'
  const groups=navGroups.map(group=>({...group,items:group.items.filter(visible)})).filter(group=>group.items.length)
  const [active,setActive]=useState(firstPage);const [data,setData]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [serviceFilter,setServiceFilter]=useState('');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('');const [sort,setSort]=useState('newest');const [page,setPage]=useState(1);const [edit,setEdit]=useState(null);const [detail,setDetail]=useState(null);const [form,setForm]=useState({});const [busy,setBusy]=useState(false);const [mobileNav,setMobileNav]=useState(false)
  const params=useMemo(()=>({page,limit:20,sort,...(search?{search}:{}),...(status?{status}:{}),...(active==='Inquiries'&&serviceFilter?{service:serviceFilter}:{}),...(active==='Inquiries'&&dateFrom?{from:dateFrom}:{}),...(active==='Inquiries'&&dateTo?{to:dateTo}:{})}),[page,search,status,sort,active,serviceFilter,dateFrom,dateTo])
  const run=useCallback(async(fn)=>{setBusy(true);setError('');setMessage('');try{const r=await fn();setMessage(r.message||'Saved successfully.');return r}catch(e){setError(e.message||'Unable to complete this action.');throw e}finally{setBusy(false)}},[])
  const load=useCallback(async()=>{setLoading(true);setError('');try{
    let result
    if(active==='Dashboard')result=await api.adminDashboard(token)
    else if(active==='Users')result=await api.adminUsersPage(token,params)
    else if(active==='Inquiries')result=await api.adminInquiries(token,params)
    else if(active==='Contact Messages')result=await api.adminContacts(token,params)
    else if(active==='Projects')result=await api.adminProjectsPage(token,params)
    else if(active==='Services')result=await api.adminServicesPage(token,params)
    else if(active==='Company Information')result=await api.adminCompany(token)
    else if(active==='Website Content')result=await api.websiteContent(token)
    else if(active==='Media Library')result=await api.adminMedia(token)
    else if(active==='Documents')result=await api.adminDocuments(token)
    else if(active==='Admin Users')result=await api.adminAccounts(token)
    else if(active==='Notifications')result=await api.adminNotifications(token)
    else if(active==='Reports')result=await api.adminReports(token)
    else if(active==='Settings')result=await api.adminSettings(token)
    const pagedSections=['Users','Inquiries','Contact Messages','Projects','Services','Media Library']
    setData(active==='Notifications'?{data:result?.data||[],unread:result?.unread||0}:pagedSections.includes(active)?result:active==='Website Content'?(Array.isArray(result?.data)?result.data:[]):result?.data??[])
  }catch(e){setError(e.message||'Unable to load data.');if(e.status===401||e.status===403){localStorage.removeItem('vsw_admin_token');onLogout()}}finally{setLoading(false)}},[active,token,params,onLogout])
  useEffect(()=>{setPage(1);setSearch('');setStatus('');setServiceFilter('');setDateFrom('');setDateTo('');setSort('newest');setData(null);setMessage('')},[active])
  useEffect(()=>{load()},[load])
  const openEdit=(row,kind)=>{setEdit({kind,row});setForm(row?{...row}:kind==='project'?{...blankProject}:kind==='service'?{...blankService}:{});setDetail(null)}
  const saveProject=async(e)=>{e.preventDefault();const payload={...form};if(form.galleryMediaIdsText?.trim())payload.galleryMediaIds=form.galleryMediaIdsText.split(',').map(x=>Number(x.trim())).filter(Boolean);await run(()=>api.saveAdminProject(token,edit.row?.id,payload));setEdit(null);load()}
  const saveService=async(e)=>{e.preventDefault();await run(()=>api.saveAdminService(token,edit.row?.id,form));setEdit(null);load()}
  const saveCompany=async(e)=>{e.preventDefault();await run(()=>api.saveAdminCompany(token,form));load()}
  const saveInquiry=async(e)=>{e.preventDefault();await run(()=>api.saveAdminInquiry(token,detail.id,{status:form.status,budget:form.budget||null,followUpDate:form.followUpDate||null,assignedAdminId:form.assignedAdminId||null}));setDetail(null);load()}
  const openInquiry=async(row)=>{try{const r=await api.adminInquiry(token,row.id);setDetail(r.data);setForm({status:r.data.status,budget:r.data.budget??'',followUpDate:r.data.followUpDate?.slice?.(0,10)||'',assignedAdminId:r.data.assignedAdminId||''})}catch(e){setError(e.message)}}
  const table=(headers,rows,render,empty)=>rows?.length?<div className="admin-table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table></div>:<div className="admin-empty">{empty||'No data available.'}</div>
  const controls=(statuses=[])=> <div className="admin-tools"><label className="admin-search"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder={`Search ${active.toLowerCase()}...`}/></label>{statuses.length>0&&<select aria-label="Filter status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>}<select aria-label="Sort records" value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select><button type="button" onClick={load} className="admin-tool-button"><RefreshCw size={15}/> Refresh</button></div>
  const pages=(data?.pages||0)>1&&<div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(page+1)}>Next</button></div>
  const field=(label,key,type='text')=><label className="admin-field" key={key}><span>{label}</span><input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>
  const textarea=(label,key)=><label className="admin-field admin-field-wide" key={key}><span>{label}</span><textarea rows="4" value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>
  const formModal=(title,submit,children)=><div className="admin-conversation-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><section className="admin-edit-modal" role="dialog" aria-modal="true"><header><h2>{title}</h2><button type="button" onClick={()=>setEdit(null)} aria-label="Close"><X size={18}/></button></header><form onSubmit={submit}><div className="admin-edit-grid">{children}</div><div className="admin-edit-actions"><button type="button" className="admin-tool-button" onClick={()=>setEdit(null)}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></section></div>

  const content=()=>{
    if(loading&&!data)return <div className="admin-empty">Loading {active.toLowerCase()}…</div>
    if(active==='Dashboard'){
      const d=data||{};const t=d.totals||{}
      const stats=[['Total Users',t.users],['Total Inquiries',t.inquiries],['New Inquiries',t.newInquiries],['Pending Inquiries',t.pendingInquiries],['Total Projects',t.projects],['Ongoing Projects',t.activeProjects],['Completed Projects',t.completedProjects],['Total Services',t.services],['Contact Messages',t.contactMessages]]
      return <><div className="admin-stats">{stats.map(([label,val])=><div key={label}><span>{label}</span><strong>{val??'No data available'}</strong></div>)}</div><div className="admin-chart-grid"><TrendChart title="Inquiries - last 14 days" rows={d.inquiryTrend||[]}/><TrendChart title="New users - last 14 days" rows={d.userTrend||[]}/><Breakdown title="Inquiry status" rows={d.inquiryStatuses||[]}/><Breakdown title="Projects by status" rows={d.projectStatuses||[]}/></div><h2 className="admin-section-title">Recent inquiries</h2>{table(['ID','Customer','Service','Status','Date'],d.recentInquiries||[],r=><tr key={r.id}><td>INQ-{r.id}</td><td>{r.name}<small>{r.email}</small></td><td>{r.service}</td><td>{r.status}</td><td>{niceDate(r.createdAt)}</td></tr>,'No inquiries found.')}<h2 className="admin-section-title">Recent users</h2>{table(['Name','Email','Status','Registered'],d.recentUsers||[],r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.status}</td><td>{niceDate(r.createdAt)}</td></tr>,'No users found.')}<h2 className="admin-section-title">Recent projects</h2>{table(['Project','Location','Category','Status','Added'],d.recentProjects||[],r=><tr key={r.id}><td>{r.title}</td><td>{r.location}</td><td>{r.category}</td><td>{r.status}</td><td>{niceDate(r.createdAt)}</td></tr>,'No projects found.')}<h2 className="admin-section-title">Recent activity</h2>{table(['Event','Details','Date'],d.recentActivity||[],r=><tr key={r.id}><td>{r.title}</td><td>{r.message}</td><td>{niceDate(r.createdAt)}</td></tr>,'No recent activity.')}</>
    }
    if(active==='Projects')return <>{controls(['Upcoming','Ongoing','Completed','On Hold'])}<div className="admin-section-actions"><button onClick={()=>openEdit(null,'project')}><Plus size={15}/> Add Project</button></div>{table(['Title','Location','Category','Status','Actions'],data?.data||[],r=><tr key={r.id}><td>{r.title}</td><td>{r.location}</td><td>{r.category}</td><td>{r.status}</td><td><button className="admin-link-button" onClick={async()=>{try{setDetail((await api.adminProject(token,r.id)).data)}catch(e){setError(e.message)}}}>View</button><button className="admin-link-button" onClick={()=>openEdit(r,'project')}>Edit</button><button className="admin-link-button danger" onClick={()=>run(()=>api.archiveAdminProject(token,r.id)).then(load)}>Archive</button></td></tr>,'No projects found.')}{pages}</>
    if(active==='Services')return <>{controls(['active','inactive'])}<div className="admin-section-actions"><button onClick={()=>openEdit(null,'service')}><Plus size={15}/> Add Service</button></div>{table(['Title','Description','Order','Status','Actions'],data?.data||[],r=><tr key={r.id}><td>{r.title}</td><td>{r.description}</td><td>{r.displayOrder}</td><td><span className={`admin-status-badge ${r.status==='active'?'is-active':'is-inactive'}`}>{r.status}</span></td><td><button className="admin-link-button" onClick={()=>openEdit(r,'service')}>Edit</button><button className="admin-link-button danger" onClick={()=>run(()=>api.deleteAdminService(token,r.id)).then(load)}>Delete</button></td></tr>,'No services available.')}{pages}</>
    if(active==='Users')return <>{controls(['active','disabled'])}{table(['ID','Name','Email','Phone','Company','Registered','Last login','Status','Actions'],data?.data||[],r=><tr key={r.id}><td>{r.id}</td><td>{r.name}</td><td>{r.email}</td><td>{r.phone}</td><td>{r.company||'—'}</td><td>{niceDate(r.createdAt)}</td><td>{niceDate(r.lastLogin)}</td><td><span className={`admin-status-badge ${r.status==='active'?'is-active':'is-inactive'}`}>{r.status}</span></td><td><button className="admin-link-button" onClick={async()=>{try{setDetail((await api.adminUser(token,r.id)).data)}catch(e){setError(e.message)}}}>View</button><button className="admin-link-button" onClick={()=>openEdit(r,'user')}>Edit</button><button className="admin-link-button danger" onClick={()=>run(()=>api.deleteAdminUser(token,r.id)).then(load)}>Delete</button></td></tr>,'No users found.')}{pages}</>
    if(active==='Inquiries')return <>{controls(statusOptions)}<div className="admin-tools"><label>From <input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setPage(1)}}/></label><label>To <input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);setPage(1)}}/></label><select aria-label="Filter inquiry service" value={serviceFilter} onChange={e=>{setServiceFilter(e.target.value);setPage(1)}}><option value="">All services</option>{[...new Set((data?.data||[]).map(x=>x.service).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></div><AdminInquiries inquiries={data?.data||[]} token={token} statuses={statusOptions} onUpdate={load} onError={setError} onView={openInquiry} onArchive={row=>run(()=>api.saveAdminInquiry(token,row.id,{archived:true})).then(load)}/>{pages}</>
    if(active==='Company Information')return <form className="admin-data-form" onSubmit={saveCompany}><div className="admin-edit-grid">{['companyName','tagline','foundedYear','phone','alternatePhone','email','whatsapp','website','address','branchOffice','city','state','country','googleMapUrl','gstNumber','cinNumber','officeHours','facebook','instagram','linkedin','youtube','twitter'].map(k=>field(({companyName:'Company name',tagline:'Tagline',foundedYear:'Founded year',phone:'Phone',alternatePhone:'Alternate phone',email:'Email',whatsapp:'WhatsApp',website:'Website',address:'Head office',branchOffice:'Branch office',googleMapUrl:'Google Maps URL',gstNumber:'GST number',cinNumber:'CIN number',officeHours:'Office hours',facebook:'Facebook',instagram:'Instagram',linkedin:'LinkedIn',youtube:'YouTube',twitter:'X / Twitter'})[k]||k,k,k==='foundedYear'?'number':'text'))}{textarea('About company','aboutCompany')}</div><button disabled={busy}>{busy?'Saving…':'Save company information'}</button></form>
    if(active==='Contact Messages')return <>{controls(['Unread','Read','Replied','Closed'])}{table(['Name','Email','Phone','Subject','Message','Date','Status','Actions'],data?.data||[],r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.phone}</td><td>{r.subject||'—'}</td><td>{r.message}</td><td>{niceDate(r.createdAt)}</td><td><select value={r.status} onChange={e=>run(()=>api.saveAdminContact(token,r.id,e.target.value)).then(load)}>{['Unread','Read','Replied','Closed'].map(s=><option key={s}>{s}</option>)}</select></td><td><button className="admin-link-button danger" onClick={()=>run(()=>api.deleteAdminContact(token,r.id)).then(load)}>Delete</button></td></tr>,<><p>No general contact messages have been submitted yet.</p><p>Project inquiries are stored separately and are available in the Inquiries section.</p><button className="admin-link-button" type="button" onClick={()=>setActive('Inquiries')}>View project inquiries</button></>)}{pages}</>
    if(active==='Website Content')return <ContentEditor data={data||[]} token={token} onSave={run} onRefresh={load}/>
    if(active==='Media Library')return <MediaLibrary data={data?.data||[]} token={token} onSave={run} onRefresh={load}/>
    if(active==='Documents')return <DocumentLibrary data={data||[]} token={token} onSave={run} onRefresh={load}/>
    if(active==='Admin Users')return <AdminAccounts data={data||[]} token={token} onSave={run} onRefresh={load}/>
    if(active==='Notifications')return <><div className="admin-section-actions"><button disabled={!data?.unread} onClick={()=>run(()=>api.markAllAdminNotifications(token)).then(load)}><CheckCheck size={15}/> Mark all read</button></div>{table(['Type','Notification','Date','Actions'],data?.data||[],r=><tr key={r.id}><td><span className={`admin-dot ${r.isRead?'read':''}`}/>{r.type}</td><td><b>{r.title}</b><small>{r.message}</small></td><td>{niceDate(r.createdAt)}</td><td>{!r.isRead&&<button className="admin-link-button" onClick={()=>run(()=>api.markAdminNotification(token,r.id)).then(load)}>Mark read</button>}<button className="admin-link-button danger" onClick={()=>window.confirm('Delete this notification?')&&run(()=>api.deleteAdminNotification(token,r.id)).then(load)}>Delete</button></td></tr>,'No notifications yet.')}</>
    if(active==='Reports')return <Reports data={data||{}} token={token} onRefresh={load}/>
    if(active==='Settings')return <SettingsPanel data={data||{}} token={token} onSave={run} onLogout={onLogout}/>
    return <div className="admin-empty">No data available.</div>
  }

  return <div className="admin-shell"><header className="admin-topbar"><button className="admin-mobile-menu" onClick={()=>setMobileNav(!mobileNav)} title="Toggle navigation"><Menu size={18}/></button><a href="/" className="brand"><span className="brand-mark">VSW</span><span className="brand-name">SOLUTIONS <i>/</i> ADMIN</span></a><div className="admin-top-actions"><span className="admin-role-pill">{admin.role.replaceAll('_',' ')}</span><button onClick={load} title="Refresh"><RefreshCw size={17}/></button><button onClick={onLogout} title="Log out"><LogOut size={17}/></button></div></header><div className="admin-body"><aside className={mobileNav?'is-open':''}>{groups.map(group=><div className="admin-nav-group" key={group.label}><small>{group.label}</small>{group.items.map(item=>{const Icon=navIcons[item]||Gauge;return <button key={item} className={active===item?'active':''} onClick={()=>{setActive(item);setMobileNav(false)}}><Icon size={16}/><span>{item}</span></button>})}</div>)}<div className="admin-profile"><span>{(admin.name||'A').slice(0,1).toUpperCase()}</span><div><b>{admin.name}</b><small>{admin.email}</small></div><button title="Log out" onClick={onLogout}><LogOut size={15}/></button></div></aside><main><div className="admin-heading"><p className="eyebrow">Workspace <span>/</span> {active}</p><h1>{active}</h1><p className="admin-heading-sub">Manage your VSW website and business records.</p></div>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}{content()}</main></div>
    {edit?.kind==='project'&&formModal(edit.row?'Edit project':'Add project',saveProject,<>{field('Project name','title')}{field('Location','location')}{field('Category','category')}{field('Client name','clientName')}{field('Project value','projectValue','number')}{field('Start date','startDate','date')}{field('Completion date','completionDate','date')}<label className="admin-field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['Upcoming','Ongoing','Completed','On Hold'].map(x=><option key={x}>{x}</option>)}</select></label>{field('Main image URL','image')}{field('Brochure / PDF URL','brochure')}{field('Gallery media IDs (comma separated)','galleryMediaIdsText')}{field('Display order','displayOrder','number')}{textarea('Description','description')}</>)}
    {edit?.kind==='service'&&formModal(edit.row?'Edit service':'Add service',saveService,<>{field('Title','title')}{field('URL slug','slug')}{field('Image URL','image')}{field('Icon name','icon')}{field('Display order','displayOrder','number')}<label className="admin-field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{textarea('Description','description')}</>)}
    {edit?.kind==='user'&&formModal('Edit user',async e=>{e.preventDefault();await run(()=>api.saveAdminUser(token,edit.row.id,form));setEdit(null);load()},<>{field('Full name','name')}{field('Email','email','email')}{field('Phone','phone')}{field('Company','company')}<label className="admin-field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></label></>)}
    {detail?.id&&active==='Inquiries'&&<div className="admin-conversation-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><section className="admin-edit-modal"><header><div><small>Inquiry INQ-{detail.id} · {detail.email}</small><h2>{detail.name} — {detail.service}</h2></div><button onClick={()=>setDetail(null)}><X size={18}/></button></header><p>{detail.message}</p><form onSubmit={saveInquiry}><div className="admin-edit-grid"><label className="admin-field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></label>{field('Budget','budget','number')}{field('Follow-up date','followUpDate','date')}<label className="admin-field"><span>Assigned admin ID</span><input type="number" value={form.assignedAdminId} onChange={e=>setForm({...form,assignedAdminId:e.target.value})}/></label></div><button disabled={busy}>{busy?'Saving…':'Save inquiry'}</button></form><Notes notes={detail.notes||[]} token={token} inquiryId={detail.id} onSaved={()=>openInquiry(detail)}/></section></div>}
    {detail?.id&&active==='Projects'&&<div className="admin-conversation-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><section className="admin-edit-modal" role="dialog" aria-modal="true"><header><div><small>Project details</small><h2>{detail.title}</h2></div><button onClick={()=>setDetail(null)} aria-label="Close"><X size={18}/></button></header>{detail.image&&<img className="admin-project-preview" src={detail.image} alt={detail.title}/>}<p>{detail.description||'No project description available.'}</p><div className="admin-settings-grid"><p><b>Location</b><span>{detail.location||'?'}</span></p><p><b>Category</b><span>{detail.category||'?'}</span></p><p><b>Client</b><span>{detail.clientName||'?'}</span></p><p><b>Status</b><span>{detail.status}</span></p></div><h3>Gallery</h3>{detail.images?.length?<div className="admin-project-gallery">{detail.images.map(image=><img key={image.id} src={image.imageUrl} alt={image.altText||detail.title}/>)}</div>:<div className="admin-chart-empty">No gallery images attached.</div>}{detail.brochure&&<p><a href={detail.brochure} target="_blank" rel="noreferrer">Open project brochure</a></p>}</section></div>}
    {detail?.id&&active==='Users'&&<div className="admin-conversation-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><section className="admin-edit-modal"><header><div><small>User #{detail.id}</small><h2>{detail.name}</h2></div><button onClick={()=>setDetail(null)}><X size={18}/></button></header><p>{detail.email} · {detail.phone} · {detail.company||'No company'} · {detail.status}</p><h3>Inquiry history</h3>{table(['ID','Service','Status','Date'],detail.inquiries||[],r=><tr key={r.id}><td>INQ-{r.id}</td><td>{r.service}</td><td>{r.status}</td><td>{niceDate(r.createdAt)}</td></tr>,'No inquiries found.')}<h3>Account activity</h3>{detail.activity?.length?detail.activity.map(item=><p className="admin-activity-item" key={`${item.type}-${item.createdAt}`}><b>{item.type.replaceAll('_',' ')}</b> ? {item.summary}<small>{niceDate(item.createdAt)}</small></p>):<div className="admin-chart-empty">No account activity recorded.</div>}</section></div>}
  </div>
}

function TrendChart({title,rows}){const values=new Map(rows.map(r=>[String(r.day).slice(0,10),Number(r.total)]));const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);const key=d.toISOString().slice(0,10);return {key,value:values.get(key)||0,label:d.toLocaleDateString(undefined,{day:'numeric',month:'short'})}});const max=Math.max(1,...days.map(x=>x.value));return <section className="admin-chart-card"><header><h3>{title}</h3><span>From live records</span></header>{rows.length?<div className="admin-bars" role="img" aria-label={title}>{days.map(d=><div key={d.key} title={`${d.label}: ${d.value}`}><i style={{height:`${Math.max(d.value?7:2,d.value/max*100)}%`}}/><small>{d.label.slice(0,2)}</small></div>)}</div>:<div className="admin-chart-empty">No records in this period.</div>}</section>}
function Breakdown({title,rows}){const total=rows.reduce((sum,x)=>sum+Number(x.total),0);return <section className="admin-chart-card"><header><h3>{title}</h3><span>{total} total</span></header>{rows.length?<div className="admin-breakdown">{rows.map((r,i)=><div key={r.status}><span><i style={{'--bar-order':i}}/>{r.status}</span><b>{r.total}</b><small>{Math.round(Number(r.total)/total*100)}%</small></div>)}</div>:<div className="admin-chart-empty">No records to summarize.</div>}</section>}
function SettingsPanel({data,token,onSave,onLogout}){const [currentPassword,setCurrent]=useState('');const [newPassword,setNext]=useState('');const submit=async(e)=>{e.preventDefault();await onSave(()=>api.changeAdminPassword(token,{currentPassword,newPassword}));setCurrent('');setNext('');onLogout()};return <div className="admin-settings-layout"><section className="admin-settings-card"><div><h2>Website & email</h2><p>Environment based settings. Sensitive values remain on the server.</p></div><div className="admin-settings-grid"><p><b>Inquiry recipient</b><span>{data.inquiryReceiverEmail||'Not configured'}</span></p><p><b>SMTP status</b><span>{data.smtpConfigured?'Configured':'Not configured'}</span></p><p><b>SMTP host</b><span>{data.smtpHost||'Not configured'}</span></p><p><b>SMTP port</b><span>{data.smtpPort||'Not configured'}</span></p><p><b>Inquiry rate limit</b><span>{data.rateLimit??'?'} requests / 15 minutes</span></p></div><p className="admin-settings-note">SMTP passwords, database credentials, and JWT secrets are never returned to the browser. Configure these in the backend environment file.</p></section><form className="admin-settings-card admin-password-form" onSubmit={submit}><div><h2>Change administrator password</h2><p>Use your current password to protect this account.</p></div><label className="admin-field"><span>Current password</span><input type="password" autoComplete="current-password" minLength="1" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required/></label><label className="admin-field"><span>New password (12 characters minimum)</span><input type="password" autoComplete="new-password" minLength="12" maxLength="72" value={newPassword} onChange={e=>setNext(e.target.value)} required/></label><button disabled={!currentPassword||newPassword.length<12}>Update password</button></form></div>}

function Notes({notes,token,inquiryId,onSaved}){const [note,setNote]=useState('');return <div className="admin-notes"><h3>Internal notes</h3>{notes.map(n=><p key={n.id}><b>{n.author||'Admin'}</b> · {niceDate(n.createdAt)}<br/>{n.note}</p>)}<form onSubmit={async e=>{e.preventDefault();await api.addInquiryNote(token,inquiryId,note);setNote('');onSaved()}}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a private note" required/><button>Add note</button></form></div>}
const contentPageFields={
  home:{section:'hero',fields:[['heading','Main heading'],['tagline','Tagline'],['description','Description',true],['buttonText','Main button text'],['buttonLink','Main button link'],['secondaryButtonText','Second button text'],['secondaryButtonLink','Second button link'],['heroImage','Hero image URL']]},
  about:{section:'main',fields:[['heading','Heading'],['description','Description',true],['intro','Intro',true],['paragraphOne','Paragraph one',true],['paragraphTwo','Paragraph two',true],['mission','Mission',true],['vision','Vision',true],['buttonText','Button text'],['image','Image URL'],['imageAlt','Image description'],['caption','Image caption']]},
  services:{section:'main',fields:[['eyebrow','Small heading'],['heading','Heading'],['description','Description',true]]},
  projects:{section:'main',fields:[['eyebrow','Small heading'],['heading','Heading'],['description','Description',true],['buttonText','Button text']]},
  contact:{section:'main',fields:[['eyebrow','Small heading'],['heading','Heading'],['description','Description',true]]},
  footer:{section:'main',fields:[['tagline','Tagline'],['subTagline','Second line'],['copyrightTagline','Copyright line']]},
}

function ContentEditor({data,token,onSave,onRefresh}){
  const [page,setPage]=useState('home')
  const [content,setContent]=useState({})
  const [json,setJson]=useState('{}')
  const [advanced,setAdvanced]=useState(false)
  const section=contentPageFields[page].section
  const rows=Array.isArray(data)?data:[]
  const row=rows.find(x=>x?.page===page&&x?.section===section)
  useEffect(()=>{
    let saved=row?.content||{}
    if(typeof saved==='string'){try{saved=JSON.parse(saved)}catch{saved={}}}
    if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={}
    setContent(saved)
    setJson(JSON.stringify(saved,null,2))
  },[row])
  const submit=async e=>{
    e.preventDefault()
    let nextContent=content
    if(advanced){
      try{nextContent=JSON.parse(json)}catch{return alert('Content JSON is invalid. Please correct it before saving.')}
      if(!nextContent||typeof nextContent!=='object'||Array.isArray(nextContent))return alert('Content must be a JSON object.')
    }
    try{
      await onSave(()=>api.saveWebsiteContent(token,{page,section,content:nextContent}))
      onRefresh()
    }catch{}
  }
  return <form className="admin-data-form" onSubmit={submit}>
    <div className="admin-content-heading"><div><h2>Edit website text</h2><p>Choose a page, update its visible text, and save it to the website.</p></div><button type="button" className="admin-tool-button" onClick={onRefresh}><RefreshCw size={15}/> Reload content</button></div>
    <div className="admin-tools"><label className="admin-field"><span>Website page</span><select value={page} onChange={e=>setPage(e.target.value)}>{Object.keys(contentPageFields).map(name=><option key={name} value={name}>{name[0].toUpperCase()+name.slice(1)}</option>)}</select></label><p>Editing the <b>{section}</b> section. Changes are shown on the public website after saving.</p></div>
    <div className="admin-edit-grid">{contentPageFields[page].fields.map(([key,label,multiline])=><label className={`admin-field${multiline?' admin-field-wide':''}`} key={key}><span>{label}</span>{multiline?<textarea rows="4" value={content[key]??''} onChange={e=>setContent(current=>({...current,[key]:e.target.value}))}/>:<input value={content[key]??''} onChange={e=>setContent(current=>({...current,[key]:e.target.value}))}/>}</label>)}</div>
    <details className="admin-content-advanced" open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)}><summary>Advanced JSON editor</summary><p>Optional: edit the complete content object directly.</p><textarea className="admin-code-editor" value={json} onChange={e=>setJson(e.target.value)} rows="14"/></details>
    <button type="submit">Save website content</button>
  </form>
}
function MediaLibrary({data,token,onSave,onRefresh}){const [file,setFile]=useState(null);const [alt,setAlt]=useState('');const [relatedType,setRelatedType]=useState('general');const [relatedId,setRelatedId]=useState('');return <><form className="admin-upload-form" onSubmit={async e=>{e.preventDefault();if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('altText',alt);fd.append('relatedType',relatedType);fd.append('relatedId',relatedId);await onSave(()=>api.uploadAdminMedia(token,fd));setFile(null);setAlt('');e.currentTarget.reset();onRefresh()}}><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={e=>setFile(e.target.files[0])}/><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Alt text / file label"/><select value={relatedType} onChange={e=>setRelatedType(e.target.value)}>{['general','project','service','banner','gallery'].map(x=><option key={x}>{x}</option>)}</select><input type="number" value={relatedId} onChange={e=>setRelatedId(e.target.value)} placeholder="Related project/service ID"/><button disabled={!file}>Upload file</button><small>JPG, PNG, WEBP, GIF, or PDF · Maximum 15 MB. Project uploads link to the gallery; service uploads set its image.</small></form><div className="admin-media-grid">{data.map(item=><article key={item.id}>{item.mediaType==='image'?<img src={`/uploads/${item.storedName}`} alt={item.altText||item.originalName}/>:<a href={`/uploads/${item.storedName}`} target="_blank" rel="noreferrer">PDF</a>}<b>{item.originalName}</b><small>{Math.round(item.fileSize/1024)} KB · {item.mimeType}</small><button className="admin-link-button" onClick={()=>{const value=window.prompt('Rename media item',item.originalName);if(value)onSave(()=>api.updateAdminMedia(token,item.id,{originalName:value})).then(onRefresh)}}>Rename</button><button className="admin-link-button danger" onClick={()=>onSave(()=>api.deleteAdminMedia(token,item.id)).then(onRefresh)}>Delete</button></article>)}</div>{!data.length&&<div className="admin-empty">No media available.</div>}</>}
function DocumentLibrary({data,token,onSave,onRefresh}){const [name,setName]=useState('');const [mediaId,setMediaId]=useState('');return <><p>Upload PDFs in Media Library, then add the uploaded file here by its media ID.</p><form className="admin-tools" onSubmit={async e=>{e.preventDefault();await onSave(()=>api.createAdminDocument(token,{name,mediaId:Number(mediaId)}));setName('');setMediaId('');onRefresh()}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Document name" required/><input value={mediaId} onChange={e=>setMediaId(e.target.value)} type="number" placeholder="Media ID" required/><button>Add document</button></form>{data.length?<div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>File</th><th>Related project</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{data.map(d=><tr key={d.id}><td>{d.name}</td><td><a href={d.url} target="_blank" rel="noreferrer">{d.fileName}</a></td><td>{d.relatedProject||'—'}</td><td>{niceDate(d.uploadedAt)}</td><td><button className="admin-link-button danger" onClick={()=>onSave(()=>api.deleteAdminDocument(token,d.id)).then(onRefresh)}>Delete</button></td></tr>)}</tbody></table></div>:<div className="admin-empty">No documents available.</div>}</>}
function AdminAccounts({data,token,onSave,onRefresh}){const [form,setForm]=useState({name:'',email:'',password:'',role:'manager'});return <><form className="admin-tools" onSubmit={async e=>{e.preventDefault();await onSave(()=>api.createAdminAccount(token,form));setForm({name:'',email:'',password:'',role:'manager'});onRefresh()}}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name" required/><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" required/><input type="password" minLength="12" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Temporary password (12+ chars)" required/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['super_admin','admin','manager','editor','support_staff'].map(x=><option key={x}>{x}</option>)}</select><button>Create admin</button></form>{data.length?<div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Added</th><th>Actions</th></tr></thead><tbody>{data.map(a=><tr key={a.id}><td>{a.name}</td><td>{a.email}</td><td><select value={a.role} onChange={async e=>{await onSave(()=>api.updateAdminAccount(token,a.id,{name:a.name,email:a.email,role:e.target.value}));onRefresh()}}>{['super_admin','admin','manager','editor','support_staff'].map(x=><option key={x}>{x}</option>)}</select></td><td>{niceDate(a.createdAt)}</td><td><button className="admin-link-button danger" onClick={()=>onSave(()=>api.deleteAdminAccount(token,a.id)).then(onRefresh)}>Delete</button></td></tr>)}</tbody></table></div>:<div className="admin-empty">No admin accounts found.</div>}</>}
function Reports({data,token,onRefresh}){const [dates,setDates]=useState({from:data.from||'',to:data.to||''});const [reportType,setReportType]=useState('inquiries');const [reportData,setReportData]=useState(data);return <><form className="admin-tools" onSubmit={async e=>{e.preventDefault();const r=await api.adminReports(token,dates);setReportData(r.data)}}><label>From <input type="date" value={dates.from} onChange={e=>setDates({...dates,from:e.target.value})}/></label><label>To <input type="date" value={dates.to} onChange={e=>setDates({...dates,to:e.target.value})}/></label><button>Apply</button><select value={reportType} onChange={e=>setReportType(e.target.value)}>{['inquiries','users','projects','services'].map(x=><option key={x}>{x}</option>)}</select><button type="button" onClick={()=>downloadCsv(`vsw-${reportType}-report.csv`,reportData.rows?.[reportType]||[])}><Download size={14}/> Export CSV</button></form><div className="admin-stats"><div><span>Users in range</span><strong>{reportData.users??'No data available'}</strong></div><div><span>Projects in range</span><strong>{reportData.projects??'No data available'}</strong></div><div><span>Services in range</span><strong>{reportData.services??'No data available'}</strong></div><div><span>Inquiry records</span><strong>{reportData.rows?.inquiries?.length??'No data available'}</strong></div></div></>}
